### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#15]
@jimhester: The `tic` package aims at providing a CI-agnostic way to specify tests and deployments. I wonder what's the best way to integrate it with `language: r` on Travis. Ideally, I'd like the Travis runner to call functions exported from tic, but I'm not sure how to provide a smooth transition for existing `.travis.yml` files.

CC @karthik.

**Comment by krlmlr** [comment]
@jimhester @jeroen: Would you support the following syntax in [`r.rb`](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb):

```yml
language: r
tic: true
```

If `tic: true`, we'd need to use [this template](https://github.com/ropenscilabs/travis/blob/4b362e39506691a08df27a53f43bc80874a45b9b/inst/templates/dot-travis.yml#L6-L26).

Ideally, this happens before we submit {tic} for review to rOpenSci.

**Comment by pat-s** [comment]
We would also put time in setting up the PR :) Maybe you can give us a hint what the best approach is to create a test setup? Following the README of "travis-build" and using docker or is there an "easier" way?

**Comment by jimhester** [comment]
I don't think it is really possible without a pretty massive refactoring of that script or adding conditionals to a bunch of blocks.

I thought the whole purpose of tic was to avoid needing to edit the `.travis.yml` at all with all of the configuration in a CI agnostic file. If so what is wrong with the current approach?

**Comment by pat-s** [comment]
> I don't think it is really possible without a pretty massive refactoring of that script or adding conditionals to a bunch of blocks.

The latter was what I had in mind. Basically, we would simply forward all stages to `tic.R`.

> I thought the whole purpose of tic was to avoid needing to edit the .travis.yml at all with all of the configuration in a CI agnostic file. If so what is wrong with the current approach?

This is correct and it still works like this. However, we would like to get rid of all the manual forwarding code

```yml
# DO NOT CHANGE THE CODE BELOW
before_install: R -q -e 'install.packages(c("remotes", "curl")); remotes::install_local(getwd(), force = TRUE); tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE
```

with the aim of having a `.travis.yml` that is as simple as 

```yml
language: r


# Header
language: r
sudo: false
dist: trusty
cache: packages
latex: false
tic: true
```

Note the possible `tic: true` option in the header. This would make our approach much more tidy for the user. 

Another possibility would be the creating of a new "travis language". However, we do not want to create redundant code and possibly travis would not accept custom language build files.
