### ISSUE TITLE
Allow early abortion of stage

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#32]
e.g., if pkgdown fails early, we generally don't want to deploy: https://travis-ci.org/r-prof/profile/jobs/320583667#L1752

**Comment by pat-s** [comment]
I just wanted to raise a similar issue. For me it even force pushed after a non-successful pkgdown build which then creates a site with lots of 404 pages.

Currently I try to make the push dependend on a successful build by using `after_success:` instead of `after_deploy:`

```yml
      deploy:
         provider: script
         script: R -q -e 'tic::deploy()'
         on:
           all_branches: true
      after_success: R -q -e 'tic::after_deploy()'
      after_script: R -q -e 'tic::after_script()'
```

together with moving `step_push_deploy()` to stage `after_deploy` which itself is called only in `after_success` in `.travis.yml`.

```r
  get_stage("deploy") %>%
    add_step(step_build_pkgdown())

  get_stage("after_deploy") %>%
    add_step(step_push_deploy(orphan = TRUE, path = "docs", branch = "gh-pages"))
```

Dirty workaround, I'll see tomorrow if the [build](https://travis-ci.org/pat-s/mlr/builds/321583802) passes.
