### ISSUE TITLE
Deploy step: Condition handling

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#76]
```yml
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
```

With the current default we have to restrict deployment for certain branches only in `tic.R`.

However, I find it practically easier to do it in `.travis.yml` than writing `ci()$get_branch() == "<branch>"` in `tic.R`.

I know we don't want to touch `.travis.yml` anymore when using tic but isn't this in this case complicating things? 

This leads to the general question whether conditioning (only for the deploy stage) is not easier done in `.travis.yml` than in tic.R?

Only because of the "provider, condition" interface for this stage.

I find

```yml
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    branch: master
    condition:
      - $TRAVIS_PULL_REQUEST = false
      - $TRAVIS_EVENT_TYPE != cron
```

way simpler to understand than 

```r
if (Sys.getenv("TRAVIS_PULL_REQUEST") == "false" && 
     Sys.getenv("TRAVIS_PULL_REQUEST") != "cron" && 
       `ci()$is_branch()` == "master") {
}
```
